/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    Divider: typeof import('primevue/divider')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Timeline: typeof import('primevue/timeline')['default']
    TimeLine: typeof import('primevue/timeline')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface GlobalDirectives {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
